"""Body measurements for revision round 1 (spec section 10): writes tar3d/bodyData.js.

Sources (photos are not stored in the repository; pass their paths):
  --front R4.jpg   body from the front, white background (outline, skin, pale lip)
  --side  R6.jpg   whole instrument, near-profile from behind (bowl depth)

The outline and the depth are measured automatically from the silhouettes (clean white
backgrounds). The skin and the pale lip were traced by eye on 2× enlarged crops with a
20 px grid, because skin stains, strings and highlights defeat colour thresholds; the traced
points (right half, photo pixels; the body is symmetric about x = 499) are listed below.
The tops and bottoms of the hearts are rounded, as on the photo, not cut square.

    python3 tar3d/tools/measure_body.py --front R4.jpg --side R6.jpg
"""
import argparse
from pathlib import Path

import numpy as np
from PIL import Image

BODY_LENGTH = 38.0          # cm, from the dimension table
R4_TOP, R4_BOTTOM, R4_CX = 262, 965, 499
R6_TOP, R6_BOTTOM = 589, 962  # body rows in the straightened photo
R6_TILT = -4.0  # degrees; found by aligning the side render with the photo

# Traced on R4: (photo row, half-width in px from the centre line).
UPPER_SKIN = [(288, 0), (289, 40), (291, 65), (295, 85), (300, 95), (310, 100), (320, 101), (340, 101), (360, 100), (380, 98), (400, 90),
              (420, 76), (440, 62), (460, 49), (480, 31), (500, 12), (506, 0)]
LOWER_SKIN = [(494, 0), (500, 8), (520, 15), (540, 32), (560, 50), (580, 70), (600, 84), (620, 95),
              (640, 120), (660, 141), (680, 150), (700, 157), (720, 162), (740, 166), (760, 167),
              (780, 166), (800, 161), (820, 148), (830, 138), (838, 120), (842, 95), (844, 60), (845, 0)]
UPPER_LIP = [(274, 0), (275, 60), (277, 90), (282, 108), (290, 118), (300, 125), (320, 132), (340, 136), (360, 137), (380, 133),
             (400, 126), (420, 116), (440, 104), (460, 91), (480, 71), (500, 49), (520, 26), (532, 0)]
LOWER_LIP = [(478, 0), (490, 30), (520, 52), (560, 85), (580, 100), (600, 110), (620, 118), (640, 150),
             (660, 176), (680, 186), (700, 191), (720, 197), (740, 201), (760, 203), (780, 203),
             (800, 201), (820, 197), (840, 190), (855, 172), (866, 145), (873, 115), (877, 80), (879, 0)]


def r4_cm(rows_px):
    s = BODY_LENGTH / (R4_BOTTOM - R4_TOP)
    return [(round((R4_BOTTOM - r) * s, 3), round(w * s, 3)) for r, w in rows_px]


def union(a, b, step=1):
    """Half-width of the union of two traced regions, sampled every `step` rows."""
    def interp(pts, r):
        rs = [p[0] for p in pts]
        if r < rs[0] or r > rs[-1]:
            return 0.0
        return float(np.interp(r, rs, [p[1] for p in pts]))
    lo = min(a[0][0], b[0][0]); hi = max(a[-1][0], b[-1][0])
    return [(r, max(interp(a, r), interp(b, r))) for r in range(lo, hi + 1, step)]


def silhouette(path, top, bottom, step, rotate=0.0):
    img = Image.open(path).convert('RGB')
    if rotate:
        # straighten a tilted photo about the neck–body joint
        img = img.rotate(rotate, resample=Image.BICUBIC, fillcolor=(255, 255, 255), center=(540, 590))
    a = np.asarray(img).astype(int)
    m = (a.min(2) < 215) | ((a.max(2) - a.min(2)) > 25)
    m[:200, :230] = False  # watermark
    out = []
    for r in range(top, bottom + 1, step):
        xs = np.where(m[r])[0]
        out.append((r, (xs.max() - xs.min()) / 2 if len(xs) > 2 else 0.0))
    return out, m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--front', required=True)
    ap.add_argument('--side', required=True)
    args = ap.parse_args()

    outline_px, _ = silhouette(args.front, R4_TOP, R4_BOTTOM, 5)
    outline = sorted(r4_cm(outline_px))

    # R6: near-profile; the silhouette width across the body is taken as the bowl depth
    # (front plane to back). The heel above R6_TOP is excluded.
    # R6 leans about 4° (the neck is not vertical); measured upright it fits best (spec 10.4).
    side_px, m6 = silhouette(args.side, R6_TOP, R6_BOTTOM, 5, rotate=R6_TILT)
    s6 = BODY_LENGTH / (R6_BOTTOM - R6_TOP)
    depth = sorted((round((R6_BOTTOM - r) * s6, 3), round(2 * w * s6, 3)) for r, w in side_px)

    skin = sorted(r4_cm(union(UPPER_SKIN, LOWER_SKIN)))
    lip = sorted(r4_cm(union(UPPER_LIP, LOWER_LIP)))

    def js(name, pts, note):
        body = ',\n  '.join(f'[{y}, {w}]' for y, w in pts)
        return f'// {note}\nexport const {name} = [\n  {body},\n];\n'

    text = (
        '// Generated by tools/measure_body.py — do not edit by hand.\n'
        '// Profiles of the body in centimetres: [y from the bottom of the kaseh, value].\n\n'
        + js('OUTLINE', outline, 'Half-width of the outline seen from the front (R4 silhouette).') + '\n'
        + js('DEPTH', depth, 'Depth of the bowl behind the skin plane (R6 silhouette, near-profile).') + '\n'
        + js('SKIN', skin, 'Half-width of the two skin hearts as one region (traced on R4).') + '\n'
        + js('LIP', lip, 'Half-width of the outer edge of the pale wooden lip round the skin (traced on R4).')
    )
    out = Path(__file__).resolve().parent.parent / 'bodyData.js'
    out.write_text(text)
    print('wrote', out, 'max half-width', max(w for _, w in outline), 'max depth', max(d for _, d in depth))


if __name__ == '__main__':
    main()
