// Single source of truth for every measurement of the tar, in centimetres.
//
// Axes: x = width (to the player's right when facing the skin), y = length (bottom of
// the kaseh = 0, head = up), z = depth (skin side = +z, the skin plane is z = 0).
//
// Sources, marked on each value:
//   std   – common Persian tar measurements
//   F1    – the user's front photo (full instrument, dark studio)
//   R4    – reference: body from the front (white background)
//   R5    – reference: head and pegs, end-on
//   R6    – reference: whole instrument, three-quarter rear
//   R2/R3 – reference: fingerboard close-up / heel close-up
// Ratios measured from the photos are recorded in docs/tar-3d/SPEC.md, section 5.

export const TOTAL_LENGTH = 95; // std

export const BODY = {
  // Revision round 1: the body is measured directly from the reference photos — the outline,
  // skin and lip from R4 (front), the depth from R6 (near-profile). The profiles themselves are
  // in bodyData.js (generated by tools/measure_body.py); the figures below summarise them.
  length: 38, // F1 0.39, R6 0.41 of total length
  topY: 38.4, // the shoulders of the naghareh round off just above the body length
  // Round 14: reshaped after the user's sample sheets (tools/body_from_samples.py): two round,
  // egg-shaped bowls with a deep waist, the skin filling the face almost to its edge.
  waistY: 22, // narrowest point of the outline

  kaseh: {
    width: 22.5, // samples: body length / width = 1.69
    depth: 19.7,
  },
  naghareh: {
    width: 18.1, // 0.8 of the kaseh width
    depth: 15.8,
  },
  waistWidth: 10.1,

  // Cross-section of the bowl is a superellipse: 2 = plain ellipse, higher = fuller back (R6).
  sectionExponent: 2.3,

  rim: {
    lipHeight: 0.4, // the varnished face stands this far above the skin; the pale lip rolls down between
  },
  // The bowl swells out beyond the flat face (R4: the silhouette is wider than the face).
  bulge: {
    faceMargin: 0.5, // varnished wood between the lip and the face edge, before the bowl curves away (R4, F1)
    minFaceRatio: 0.7, // where there is no lip, the face is this fraction of the bowl width
    minOverhang: 0.2, // the bowl always stands at least this far out beyond the face edge
    widestAt: 0.28, // the bowl is widest this fraction of its depth behind the face
  },
  valley: {
    // carved diagonal groove on the back between the two bowls (R6)
    angleDeg: 25, // from horizontal, seen from the back
    depth: 1.2, // round 14: the deep waist itself now separates the bowls
    width: 4.5,
  },
};

export const NECK = {
  bottomY: BODY.length, // the neck leaves the body at its top
  boardEndY: 36.2, // the fingerboard runs down onto the naghareh, just over the upper skin (F1)
  nutY: TOTAL_LENGTH - 13, // = 82; the head is 13 cm (see HEAD.height)
  widthAtNut: 3.5, // R2 / R5
  widthAtBody: 4.1, // R4: 0.16 of the kaseh width
  depthAtNut: 2.6, // R6: back of the neck below the top of the neck wood
  depthAtBody: 3.0,
  topZ: 0.6, // top of the neck wood (the fingerboard sits on it)
  sectionExponent: 2.2, // rounded D section
  cornerRadius: 0.2, // rounded top edges of the neck wood
  fingerboard: {
    thickness: 0.25,
    centreStrip: 0.9, // dark wood strip between the two bone strips (R2, F1)
    bevel: 0.03,
  },
  nut: { height: 0.45, length: 0.6, radius: 0.12, slots: 6 },
};

export const HEEL = {
  // pointed tongue running from the neck down the back of the naghareh (R3, R6)
  length: 10, // below the top of the body
  startY: 42, // the back of the neck starts to thicken here, above the body (R6)
  neckBulge: 0.6, // extra depth of the neck back where it reaches the body
  tipWidth: 1.2,
  thicknessTop: 0.5, // stand-off from the bowl where the neck meets it (matches neckBulge)
  thicknessMid: 1.0,
  thicknessTip: 0.8, // R3: the nose stays thick and rounded
  noseLength: 1.2, // rounded end of the tongue
};

export const HEAD = {
  height: TOTAL_LENGTH - NECK.nutY, // = 13 (F1: 0.134 of total length)
  width: 4.0, // F1: slightly wider than the neck at the nut
  depth: 3.4,
  // From the top of the head (R5). The slot opens right behind the nut so the strings can
  // run from the nut straight down to their pegs.
  slot: { width: 1.6, top: 1.5, bottom: 12.7 },
  wall: 0.6, // back wall behind the slot
  cornerRadius: 0.3,
  bevel: 0.08, // softened edges of the head block
  // Cusped (three-lobed) cut-outs at both ends of the slot (R5)
  cusp: { centreRadius: 0.55, sideRadius: 0.32, sideOffset: 0.5, height: 1.0 },
  crown: { count: 3, height: 1.0 }, // round 14: carved pyramids on top (samples)
};

// Pegs: three each side, staggered (R5). `at` is the distance from the top of the head
// as a fraction of its height; side −1 = left (−x), +1 = right (+x).
export const PEGS = {
  knobDiameter: 3.2,
  knobLength: 2.6,
  collarDiameter: 1.6,
  shaftDiameter: 1.0,
  shaftTipDiameter: 0.75,
  reach: 5.2, // how far the knob end stands out from the head wall (F1)
  layout: [
    { side: -1, at: 0.29, string: 1 },
    { side: +1, at: 0.32, string: 2 },
    { side: +1, at: 0.49, string: 3 },
    { side: -1, at: 0.59, string: 4 },
    { side: -1, at: 0.82, string: 5 },
    { side: +1, at: 0.87, string: 6 },
  ],
};

export const SCALE_LENGTH = 68; // std 66–69; nut to bridge
export const BRIDGE = {
  y: NECK.nutY - SCALE_LENGTH, // = 14 cm above the bottom of the kaseh (F1/R4: 0.32–0.37 of the body)
  width: 5.4, // R4
  height: 1.0,
  thickness: 0.5,
  footWidth: 1.4, // two feet with an arch between them
};

export const TAILPIECE = {
  width: 2.6,
  length: 2.8, // R4: sits on the wood below the lower skin opening
  y0: 0.2, // bottom end, just above the bottom of the kaseh
  thickness: 0.4,
  pinY: 1.2, // where the strings are hooked
  radius: 0.15,
};

// Six strings in three courses. Gauges are diameters in cm.
export const STRINGS = {
  spanAtNut: 1.9, // outer string to outer string
  spanAtBridge: 3.4,
  spanAtTail: 1.8,
  pairGap: 0.5, // between the two strings of a course, at the bridge
  coilTurns: 3, // turns wound on each peg shaft
  coilWidth: 0.35,
  gauges: [0.025, 0.025, 0.03, 0.03, 0.035, 0.05],
  wound: [false, false, false, false, false, true], // the low course has one wound bronze string
};

export const FRETS = {
  strandDiameter: 0.08, // gut strand (R2)
  strands: 4, // turns per fret
  strandsLite: 2, // turns per fret on the light quality level
  jitter: 0.02, // hand-tied turns are never perfectly even (cm)
  knotRadius: 0.11, // knot on the bass side of the neck (R2)
  tailLength: 0.35,
  nailHead: 0.09, // radius of the nail heads where a fret cannot wrap the back (R3)
};

// Pivot of the whole instrument: the visual centre of its bounding box, so it turns
// evenly about any axis.
export const PIVOT = { x: 0, y: TOTAL_LENGTH / 2, z: -BODY.kaseh.depth / 2 + 1.5 };

// Quality levels: one switch controls mesh density, texture size and shadow quality.
export const QUALITY = {
  high: { bodyStations: 220, bodyRadial: 144, fretTurns: FRETS.strands, texture: 2048, shadow: 2048 },
  lite: { bodyStations: 120, bodyRadial: 72, fretTurns: FRETS.strandsLite, texture: 1024, shadow: 1024 },
};
